# Generated by Django 2.1.1 on 2018-09-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('coinName', models.CharField(max_length=100)),
                ('fullName', models.CharField(max_length=200)),
                ('baseUrl', models.CharField(max_length=1000)),
                ('imageUrl', models.CharField(max_length=1000)),
                ('overviewUrl', models.CharField(max_length=1000)),
                ('isTrading', models.BooleanField()),
            ],
        ),
    ]
