# Generated by Django 2.1.1 on 2018-09-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='baseUrl',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='fullName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='overviewUrl',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
