# Generated by Django 2.1.1 on 2018-09-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180916_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=200)),
                ('isTrading', models.BooleanField()),
                ('logoUrl', models.CharField(blank=True, max_length=1000)),
                ('sponsored', models.BooleanField(blank=True)),
                ('recommended', models.BooleanField(blank=True)),
                ('affiliatedUrl', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
