# Generated by Django 2.1.1 on 2018-09-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCoinOrigin', models.IntegerField()),
                ('idCoinDestiny', models.IntegerField()),
                ('idExchange', models.IntegerField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('open', models.FloatField()),
                ('timestamp', models.IntegerField()),
                ('volumeOrigin', models.FloatField()),
                ('volumeDestiny', models.FloatField()),
            ],
        ),
    ]
